# Author: Artem Bakhtin
openapi: 3.1.0
info:
  title: Quarkus Tika API
  version: 1.0.0
  description: API for extracting text from PDF and ODT files using Apache Tika on Quarkus.
servers:
  - url: http://localhost:{port}
    variables:
      port:
        default: '8004'
        description: The port number of the server
paths:
  /parse/text:
    post:
      summary: Extract text from a document
      description: Extracts plain text from a PDF or ODT document.
      requestBody:
        required: true
        content:
          application/pdf:
            schema:
              type: string
              format: binary
            examples:
              samplePDF:
                summary: Example PDF file
                externalValue: "quarkus.pdf"
          application/vnd.oasis.opendocument.text:
            schema:
              type: string
              format: binary
            examples:
              sampleODT:
                summary: Example ODT file
                externalValue: "quarkus.odt"
      responses:
        '200':
          description: Extracted plain text
          content:
            text/plain:
              schema:
                type: string