# Author - Artem Bakhtin

openapi: 3.0.3
info:
  title: Micronaut Shopcart API
  version: 1.0.0
  description: API for managing a shopping cart application

servers:
  - url: http://localhost:{port}
    variables:
        port:
          default: '8001'
          description: The port number of the server
paths:
  /:
    post:
      summary: Create a new client
      operationId: addClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - name
              properties:
                username:
                  type: string
                  description: The username of the client
                name:
                  type: string
                  description: The name of the client
            examples:
              newClient:
                value: '{"username": "john_doe", "name": "John Doe"}'
      responses:
        '200':
          description: Client created successfully
          content:
            text/plain:
              schema:
                type: string
                description: Client information
              example: "Client{id='john_doe', name='John Doe'}"
        '400':
          description: Invalid input
  /cart:
    post:
      summary: Add a product to a client's shopping cart
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - name
                - amount
              properties:
                username:
                  type: string
                  description: The username of the client
                name:
                  type: string
                  description: The name of the product
                amount:
                  type: string
                  description: The amount of the product to add
            examples:
              addBananas:
                summary: Add bananas to cart
                value: '{"username": "john_doe", "name": "bananas", "amount": "7"}'
      responses:
        '200':
          description: Product added successfully
          content:
            text/plain:
              schema:
                type: string
                description: Product information or success message
              example: "Product{name='bananas', amount='7'} added to client john_doe"
        '400':
          description: Invalid input or client not found
          content:
            text/plain:
              schema:
                type: string
                description: Error message
              example: "Error, no such client: {username: john_doe, name: bananas, amount: 7}"
  /cart/{username}:
    get:
      summary: Get a client's shopping cart
      operationId: getCart
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          example: 'john_doe'
          description: The username of the client whose cart is to be retrieved
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
            examples:
              getCartExample:
                value: ''
      responses:
        '200':
          description: Shopping cart retrieved successfully
          content:
            text/plain:
              schema:
                type: string
                description: The shopping cart information
              example: "ShoppingCart{products=[Product{name='bananas', amount='7'}, Product{name='joghurt', amount='12'}]}"
        '400':
          description: Invalid input or client not found
          content:
            text/plain:
              schema:
                type: string
                description: Error message
              example: "Error, no such client: john_doe"
